### PR TITLE
Update example notebooks

### PR DESCRIPTION
**Pull request by plakrisenko**

### CODE REVIEW

**Review by dweindl — COMMENTED** [review]
Great, thanks!

Could you please:
- [ ] unexclude that notebook in `doc/conf.py`
- [ ] add that notebook to `doc/example.rst`
- [ ] clear all notebook outputs (output will be generated on RTD)

**Comment by plakrisenko** [comment]
>     clear all notebook outputs (output will be generated on RTD)
why?

**Comment by dweindl** [comment]
> > ```
> > clear all notebook outputs (output will be generated on RTD)
> > ```
> 
> why?

To not litter the repository. Running the current examples and committing the output always adds 5MB. Unnecessary.

**Review by dweindl — APPROVED** [review]
LGTM.

Do we still need `example/example_visualization_without_visspec.ipynb` or is that redundant?

**Pull request merged**
