### PR TITLE
fix override check for empty measurement table

### PR DESCRIPTION
**Pull request by FFroehlich**

### CODE REVIEW

**Review by dweindl — APPROVED** [review]
Not meaningful to call that function without a measurement table, but the change doesn't hurt either. Update typehint?

**Review by yannikschaelte — APPROVED** [review]

**Comment by yannikschaelte** [comment]
was the merge to master intended?

**Comment by FFroehlich** [comment]
> was the merge to master intended?

no 🙈

**Comment by paulstapor** [comment]
Still... can we have that merged soon? Need it in parPE, as it breaks CI...

**Pull request merged**
